Добавил решение задачи 8,4
js-tasks-ru/jsbasic-20201008_tvisher pull request #11
Opened 2020-11-15 17:04 UTC by Tvisher

2020-11-15 17:16 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 8-module/4-task/task.test.js — добавлен
```

2020-11-16 21:57 UTC, stas-dolgachov requested changes

2020-11-16 21:57 UTC, stas-dolgachov commented on 8-module/4-task/index.js
> +    if (!this.cartItems.length) {
Можно сразу возвращать
```
return !this.cartItems.length;
```

2020-11-16 21:57 UTC, stas-dolgachov commented on 8-module/4-task/index.js
> +    let totalCount = this.cartItems.reduce((value, item) => {
👍

2020-11-16 21:57 UTC, stas-dolgachov commented on 8-module/4-task/index.js
> +    let totalPrice = this.cartItems.reduce((value, item) => {
👍

2020-11-16 21:57 UTC, stas-dolgachov commented on 8-module/4-task/index.js
> +    this.modal.remove();
Это все должен делать компонент модального окна. Вы здесь дублируете функционал, который уже там реализован. Переделайте, пожалуйста, на использование Modal (import Modal from '../../7-module/2-task/index.js';)

2020-11-17 13:23 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Корзина, часть 2
+ добавление товара должно обновить иконку корзины
+ должна измениться общая стоимость
+ должно измениться общее количество товаров
+ должно измениться общее количество товаров
+ должна измениться общая стоимость
+ корзина должна быть пустой после создания
+ корзина должна быть не пустой после добавления товара
+ должна предотвращать перезагрузку страницы
+ должна удалять все товары из корзины
+ должна отображать текст о размещении заказа
+ должна менять заголовок модальному окну
+ должна отправлять заказ
+ должна отображать увеличение общей стоимости товара
+ должна отображать увеличение товара на единицу
+ дол��на отображать увеличение стоимости товара
+ должна отображать уменьшение товара на единицу
+ должна отображать уменьшение общей стоимости товара
+ должна отображать уменьшение стоимости товара
+ должна удалять товар из корзины если его количество равно 0
+ должна закрывать модальное окно если товаров в корзине не осталось
+ должна отображать форму заказа
+ должна задавать заголовок модальному окну
+ должна отображать карточку товара
+ должна открывать модальное окно
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-11-18 06:50 UTC, stas-dolgachov approved these changes

2020-11-18 06:50 UTC, merged